
export const cardData = [
    { id:1,
      frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
      backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625332/01_Michael_zhpfof.jpg',
    },
  
    {  id:2,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625335/02_Gabriel_jep3uu.jpg',
      },
   
      { id:3,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625335/03_raphael_w3rqa1.jpg',
      },
   
      { id:4,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625338/04_uriel_uggj37.jpg',
      },
   
      { id:5,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625337/05_Metatron_fveirj.jpg',
      },
   
      { id:6,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625341/06_Chamuel_z4aaok.jpg',
      },
   
      { id:7,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625338/07_Zadkiel_jvqeup.jpg',
      },
   
      { id:8,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625339/08_Jophiel_vp6xih.jpg',
      },
   
      { id:9,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625335/09_Raguel_scnhva.jpg',
      },
   
      { id:10,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625339/10_Azrael_zssoc8.jpg',
      },
     
      
      { id:11,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625337/11_Sandalphon_cw8zeu.jpg',
      },
   
      { id:12,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/12_Raziel_o6n5o3.jpg',
      },
   
      { id:13,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625339/13_Ariel_x66uvz.jpg',
      },
   
      { id:14,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/14_jeremiel_gxsgtl.jpg',
      },
     
      
      { id:15,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625333/15_haniel_qr94vx.jpg',
      },
   
      { id:16,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625340/16_merlin_abuffh.jpg',
      },
   
      { id:17,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625339/17_Nostradamus_hl6gun.jpg',
      },
   
      { id:18,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625340/18_rumi_sneurb.jpg',
      },
     
    
      { id:19,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625345/19_Sanat_kumara_lfs6ff.jpg',
      },
   
      { id:20,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625340/20_mansa_musa_jsys9f.jpg',
      },
   
      { id:21,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625340/21_rasputin_ob9avp.jpg',
      },
   
      { id:22,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625341/22_quan_yin_awqczd.jpg',
      },
   
      { id:23,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625342/23_green_tara_xi8ixe.jpg',
      },
   
      { id:24,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625341/24_gaia_wh75og.jpg',
      },
   
      { id:25,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625345/25_isis_pdmt1u.jpg',
      },
   
      { id:26,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625345/26_jesus_msqq2y.jpg',
      },
   
      { id:27,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625342/27_buddha_qstenp.jpg',
      },
   
      { id:28,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625342/28_sai_pthqz0.jpg',
      },
   
      { id:29,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625342/29_guru_nanak_ytvq1r.jpg',
      },
     
    
      { id:30,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625343/30_mahavatar_y2bcnn.jpg',
        Message: "Practice Yoga and Meditation.",
        Colour: "Radiant White",
        CrystalorDivinationTool: "Breath Work",
        Description:"Mahavatar Babaji, the timeless and immortal yogi, is revered as the great master who reintroduced the ancient practice of Kriya Yoga to the modern world. Known as the `deathless` master, Babaji is believed to have transcended the limitations of the physical body, existing eternally to guide and uplift humanity. His teachings focus on the realization of the divine self through deep meditation and disciplined spiritual practice. Babaji’s presence is felt by those on the path of spiritual awakening, offering guidance, protection, and profound inner transformation. Mahavatara Babaji, is the Himalayan yogi and guru who taught Kriya Yoga to Lahiri Mahasaya. Babaji first became recognized through the writings of Paramahansa Yogananda, who devoted a chapter of his book, Autobiography of a Yogi, to Babaji",
        Guidance:"Drawing the card of Mahavatar Babaji as your spirit guide signifies a time to embrace the practice of yoga and meditation, to seek spiritual enlightenment. His message encourages you to deepen your meditation practice and live with spiritual discipline and devotion. Engage in practices that enhance your spiritual growth, such as daily meditation, yoga, and studying sacred texts. Mahavatar Babaji reminds you that through dedicated practice and inner focus, you can achieve profound spiritual transformation and connect with the eternal wisdom of your soul.",
        Affirmation:"I embrace the eternal wisdom and practice of yoga. With Mahavatar Babaji's guidance, I cultivate spiritual discipline and seek self-realization.",
        Invocation: "Dear Mahavatar Babaji, Eternal Yogi, I call upon your divine presence and wisdom. Illuminate my path with your timeless guidance and grace. Help me transcend my current struggles and unveil the deeper truths of my soul. Grant me your infinite compassion and serenity, and empower me to walk in alignment with my highest purpose. May your eternal light inspire and transform my journey towards enlightenment and inner peace.",

      },
   
      { id:31,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625342/31_mother_mary_ccatqs.jpg',
        Message: "Unconditional Love and Divine Nurturing.",
       Colour: "Light Blue and White",
CrystalorDivinationTool: "Blue Lace Agate",
Description:"Mother Mary, the revered mother of Jesus Christ, is a symbol of divine grace, compassion, and unconditional love. Known as the Virgin Mary in Christian tradition, she is venerated for her purity, humility, and profound faith. Mary’s acceptance of her role as the mother of Jesus exemplifies her deep devotion to God and her willingness to serve humanity. As a spiritual figure, she is often invoked for comfort, healing, and guidance, offering a motherly presence to those in need. Mother Mary's legacy of love and mercy continues to inspire people worldwide, embodying the virtues of kindness, nurturing, and spiritual strength. Mother Mary serves as a spirit guide for those seeking to cultivate love, compassion, and healing in their lives.",
Guidance:"Drawing the card of Mother Mary as your spirit guide signifies a time to embrace unconditional love and divine nurturing. Her message encourages you to practice compassion and understanding towards yourself and others. Engage in practices that enhance your emotional and spiritual growth, such as prayer, meditation, and acts of kindness. Mother Mary reminds you that through love and nurturing, you can heal and transform your life and the lives of those around you.",
Affirmation:"I embrace unconditional love and divine nurturing. With Mother Mary's guidance, I open my heart to compassion and healing.",
Invocation: "Dear Mother Mary, Divine Nurturer, I seek your gentle guidance and nurturing embrace. Illuminate the hidden needs within my heart and reveal the path of healing. Intervene in the areas of my life where I am struggling, and help me to view my challenges through a lens of love and compassion. Assist me in cultivating inner peace and purposeful living, reflecting your divine grace in all I do.",

      },
   
      { id:32,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625345/32_white_buffalo_grnbi8.jpg',
        Message: "Commit to Peace, Spiritual Wisdom, and Sacred Traditions.",
Colour: "White and Gold",
CrystalorDivinationTool: "White Buffalo, Turquoise and Clear Quartz",
Description:"White Buffalo Calf Woman, a revered figure in Lakota and other Plains Native American traditions, embodies the essence of peace, spiritual wisdom, and the sacredness of life. Her presence is symbolized by the pure white and gold colors,representing purity, spiritual enlightenment, and the deep connection to sacred traditions. White Buffalo Calf Woman serves as a spirit guide for those seeking to cultivate inner peace, spiritual growth, and a deep respect for the sacred. Her energy is one of profound peace and sacred wisdom, making her a powerful ally for those on a journey of spiritual discovery and reverence.",
Guidance:"Drawing the card of White Buffalo Calf Woman signifies a time to embrace peace, spiritual wisdom, and sacred traditions. Her message encourages you to cultivate a deep respect for the sacredness of life and to seek wisdom through spiritual practice. Engage in practices that enhance your spiritual growth and connection to sacred traditions, such as meditation, prayer, and learning about indigenous teachings. White Buffalo Calf Woman reminds you that through peace and respect for the sacred, you can achieve profound spiritual growth and inner harmony.",
Affirmation:"I embrace peace, spiritual wisdom, and sacred traditions. With the guidance of White Buffalo Calf Woman, I cultivate inner harmony and reverence for all life.",
Invocation: "Honored White Buffalo Calf Womansacred teacher of wisdom and unity, I call upon your presence. Guide me through the lessons I require to learn, illuminating the path to healing and harmony. Help me release the burdens of pain and embrace your teachings of balance and compassion. May your spirit inspire me to live with integrity and purpose, reflecting the sacred values you embody."

      },
      { id:33,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625346/33_dolores_cannon_cxoae7.jpg',
        Message: "Explore the Mysteries Within and Beyond.",
      Colour: "Deep Violet",
CrystalorDivinationTool: "Books written by Dolores Cannon.",
Description:"Dolores Cannon, a trailblazer in the field of past life regression and quantum healing hypnosis, dedicated her life to exploring the hidden realms of the human soul and the universe. With over four decades of experience in hypnosis, she developedthe Quantum Healing Hypnosis Technique (QHHT), which allows individuals to access past lives, higher consciousness, and the vast knowledge of the subconscious mind. Dolores's work delves into topics such as reincarnation, extraterrestrial encounters, and the New Earth, offering profound insights into the nature of reality and the purpose of human existence. Her books and teachings have inspired many to seek deeper understanding and explore the limitless possibilities of the soul's journey. As a pioneer of hypnotic exploration, Dolores Cannon's legacy continues to open doors to the unknown, guiding seekers on a transformative journey of discovery and awakening.",
Guidance:"Drawing the card of Dolores Cannon as your guide signifies a time to explore the mysteries of your soul and the universe. Her message encourages you to be open to new perspectives and to seek the deeper truths that lie beyond the surface of everyday life. Engage in practices that expand your consciousness, such as meditation, past life regression, or exploring spiritual literature. Dolores reminds you that the answers you seek are within you, waiting to be uncovered through inner exploration and connection with your higher self.",
Affirmation:"I am open to the mysteries of the universe. With Dolores Cannon's guidance, I explore the depths of my soul and uncover the wisdom within.",
Invocation: "Dear Dolores Cannon, guide me with your profound wisdom and insight. Help me to explore the mysteries within my soul and the vast universe beyond. Illuminate the path of my spiritual journey, revealing the truths that will aid in my growth and understanding. With your guidance, I embrace the unknown and trust in the wisdom of my higher self. Lead me to the discoveries that will transform my life and expand my consciousness."

      },
      { id:34,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625343/34_louise_hay_ah0hvd.jpg',
        Message: "Heal Your Life with Self Love and Forgiveness.",
Colour: "Soft Pink",
CrystalorDivinationTool: "Mirror and Journal",
Description:"Louise Hay, a pioneering figure in the field of self- healing and personal development, dedicated her life to helping others realize the power of positive thinking and self-love. As an author, motivational speaker, and founder of Hay House, she revolutionized the way people view their thoughts and their impact on physical and emotional well- being. Her groundbreaking book, You Can Heal Your Life, introduced millions to the concept of affirmations and the idea that our thoughts create our reality. Louise's teachings emphasize the importance of self-compassion, forgiveness, and the belief that everyone has the power to transform their life by changing their mindset. Her legacy as a healer of hearts continues to inspire and empower individuals on their journey to self-discovery and holistic health.",
Guidance:"Drawing the card of Louise Hay as your guide signifies a time to focus on healing your mind and nurturing your spirit. Her message encourages you to pay close attention to your thoughts and beliefs, as they are powerful tools in shaping your reality. Engage in practices that promote self-love, such as daily affirmations, journaling, and self-care rituals. Louise reminds you that by changing your thoughts, you can heal your life and create a future filled with love, peace, and fulfillment.",
Affirmation:"I nurture my thoughts with love and compassion. With Louise Hay's guidance, I heal my life and embrace my inner power.",
Invocation: "Dear Louise Hay, guide me with your wisdom and loving energy. Help me to heal my mind and nurture my spirit through positive thoughts and affirmations. Illuminate the path to self-love and inner peace, so I may transform my life with grace and compassion. Teach me to embrace my power and create a reality that reflects the love and joy within me.",

      },
      { id:35,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625343/35_Lord_Shiva_jrl4q3.jpg',
        Message: "Rise Through Destruction and Rebirth.",
        Colour: "Deep Blue",
        CrystalorDivinationTool: "Shiv Ling",
        Description:"Lord Shiva, one of the principal deities in Hinduism, is revered as the Supreme Being known as the `Destroyer` and “Transformer” within the Hindu trinity (Brahma, Vishnu, Mahesh – Creator, Preserver, Destroyer), Shiva's role is to dissolve the universe at the end of each cycle, paving the way for rebirth and renewal. He is often depicted in deep meditation, symbolizing his mastery over time and space, and his ability to transcend the physical world. Shiva is also worshipped as Nataraja, the cosmic dancer who represents the rhythmic movement of the universe. His powerful yet compassionate nature makes him a source of strength, transformation, and spiritual enlightenment for devotees.",
Guidance:"Drawing the card of Lord Shiva as your spirit guide signifies a time to embrace transformation and inner strength. His message encourages you to welcome change and use it as an opportunity for growth and renewal. Engage in practices that enhance your spiritual and personal development, such as meditation, yoga, and self-reflection. Lord Shiva reminds you that through inner strength and spiritual discipline, you can overcome obstacles and transform your life.",
Affirmation:
"I embrace transformation and inner strength. With Lord Shiva's guidance, I transcend limitations and harness my divine power.",
Invocation: "Om Namah Shivaya, Lord Shiva, Divine Transformer, illuminate my path with your wisdom and grace, revealing the truths hidden within my soul. Guide me through my struggles, transforming pain into strength and confusion into clarity. Assist me in embracing change with courage and equanimity, so I may live with purpose and inner peace. Bless me with your profound transformation and divine insight.",

      },
      { id:36,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625346/36_lakshmi_miu2jj.jpg',
        Message: "Embody Prosperity, Beauty, and Grace.",
Colour: "Gold and Red",
CrystalorDivinationTool: "Lotus Flower and Owl",
Description:"Goddess Lakshmi, the Hindu deity of wealth, prosperity, and abundance, is revered as the embodiment of beauty, fortune, and spiritual prosperity. She is often depicted seated on a lotus flower, symbolising purity, growth, and the unfolding of inner wisdom. As the consort of Lord Vishnu, Lakshmi plays a vital role in the preservation and nurturing of the universe. Devotees worship her to attract material and spiritual wealth, seeking her blessings for success, happiness, and harmony in their lives. Goddess Lakshmi’s presence inspires generosity, gratitude, and a deep connection to the flow of abundance in all aspects of life.",
Guidance:"Drawing the card of Goddess Lakshmi as your spirit guide signifies a time to embrace prosperity, beauty, and abundance in your life. Her message encourages you to cultivate a positive mindset and practice gratitude for the blessings you have. Engage in practices that attract prosperity, such as affirmations, visualisation, and acts of generosity. Goddess Lakshmi reminds you that through gratitude and positive intention, you can attract and sustain prosperity and beauty in all areas of your life.",
Affirmation:
"I embrace prosperity, beauty, and grace. With Goddess Lakshmi's guidance, I attract wealth and blessings with a grateful heart.",
Invocation: "Dear Goddess Lakshmi, divine source of prosperity, I call upon you with an open heart. Illuminate my path and reveal the true nature of my needs. Bring your grace into every area of my life, where I seek prosperity and fulfilment. Guide me to embrace wealth and manifest my highest potential. Help me live with gratitude and purpose, reflecting your boundless generosity.",

      },
      { id:37,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625344/37_durga_r6rgy8.jpg',
        Message: "Integrate Your Fierce Power.",
Colour: "Red",
CrystalorDivinationTool: "Red Jasper, Trishul, Sword, Lotus, Conch, Lion",
Description:"Maa Durga, the revered goddess in Hindu mythology, symbolises the embodiment of divine feminine power and strength. She is known as the fierce protector and warrior goddess who combats evil forces and restores cosmic balance. Often depicted riding a lion or tiger, with multiple arms carrying weapons, Maa Durga represents the fierce and nurturing aspects of motherhood. She is worshipped with great devotion during the festival of Navratri, where her nine forms, collectively known as Navadurga, are honored. Devotees seek her blessings for protection, courage, and the ability to overcome life's challenges, viewing her as the ultimate force of good against evil.",
Guidance:"Drawing the card of Goddess Durga as your spirit guide signifies a time to embrace your inner strength and courage. Her message encourages you to stand strong in the face of adversity and to protect what is important to you. Engage in practices that enhance your personal power and resilience, such as fasting, physical exercise, and spiritual rituals. Goddess Durga reminds you that through inner strength and fierce determination, you can overcome any challenge and protect yourself and those you love.",
Affirmation:
"I embrace my inner strength and fierce protection. With Goddess Durga's guidance, I stand strong and overcome all challenges.",
Invocation: "Glorious Goddess Durga, mighty warrior of divine strength and wisdom, bless me with your courage to face challenges and your clarity to discern truth. Guide me through the battles of my life, dispelling darkness and illuminating my path with your fierce grace. Empower me to embrace my inner strength and transform adversities into opportunities for growth and enlightenment. Bless me with your unwavering presence and protection."

      },
      { id:38,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625346/38_krishna_nut0j4.jpg',
        Message: "Let Divine Love and Playful Wisdom Flow.",
Colour: "Blue",
CrystalorDivinationTool: "Peacock feather, flute",
Description:"Bal Krishna, one of the most dear deities in Hinduism, is revered as the Supreme God, symbolising love, wisdom, and divine joy. He is the central figure in the epic Mahabharata and the Bhagavad Gita, where he imparts spiritual wisdom to Arjuna on the battlefield of Kurukshetra. Known for his playful childhood, enchanting flute music,and divine teachings, Krishna embodies the essence of dharma and bhakti. His life and teachings inspire millions to live with love, compassion, and devotion. Krishna’s teachings emphasize the importance of surrendering to the divine will and leading a life of integrity and joy.",
Guidance:"Drawing the card of Bal Krishna as your spirit guide signifies a time to embrace divine love and playful wisdom. His message encourages you to live with joy, compassion, and an open heart. Engage in practices that enhance your spiritual and emotional growth, such as devotional singing (bhajans), reading sacred texts like the Bhagavad Gita, and spending time in nature. Bal Krishna reminds you that through pure childlike love, joy, and wisdom, you can transcend life's challenges and find a deeper connection to the divine.",
Affirmation:
"I embrace divine love and playful wisdom. With Bal Krishna's guidance, I live joyfully and navigate life with enthusiasm and wisdom.",
Invocation: "Divine Krishna, guide of eternal wisdom, illuminate my path with your grace and understanding. Show me the way to transform my struggles into opportunities for growth. Grant me clarity and strength, so I may embrace life with love and purpose. Help me reflect your divine qualities in my actions, living harmoniously and fulfilling my true potential.",

      },
      { id:39,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625343/39_saraswati_uhzlex.jpg',
        Message: "Embrace Wisdom, Creativity, and Learning.",
Colour: "White and Yellow",
CrystalorDivinationTool: "Veena, Swan and Peacock",
Description:"Goddess Saraswati, the Hindu deity of wisdom, knowledge, and the arts, is revered as the divine source of all learning and creative inspiration. She is often depicted seated on a white lotus, symbolizing purity and enlightenment, with a veena (a musical instrument) in her hands, representing the harmony of music and arts. Saraswati is the embodiment of intellectual and spiritual growth, guiding her devotees towards truth and self-realization through education and creativity. As the goddess of speech and eloquence, she is invoked by students, artists, and scholars seeking wisdom, clarity, and mastery in their respective fields. Saraswati’s blessings are essential for the cultivation of knowledge, creativity, and the pursuit of higher learning.",
Guidance:"Drawing the card of Goddess Saraswati as your spirit guide signifies a time to embrace wisdom, creativity, and learning. Her message encourages you to cultivate your intellectual and artistic talents. Engage in practices that enhance your knowledge and creative expression, such as studying, playing music, writing, and engaging in artistic activities. Goddess Saraswati reminds you that through dedication to learning and creativity, you can achieve anything you desire and inspire others with your gifts.",
Affirmation:
"I embrace wisdom, creativity, and learning. With Goddess Saraswati's guidance, I unlock the power of knowledge and artistic expression.",
Invocation: "Dear Goddess Saraswati, divine embodiment of knowledge and wisdom, I seek your guidance. Illuminate my path to understanding and insight within me. Help me to discern truth from illusion, and inspire clarity in my thoughts and actions. May your presence foster enlightenment in all my endeavours, enabling me to embody your grace and wisdom in my journey. Guide me to grow in wisdom and purpose."

      },
      { id:40,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625344/40_ganesha_ftuxul.jpg',
        Message: "Welcome New Beginnings and Measure what Matters.",
Colour: "Red",
CrystalorDivinationTool: "Modak and Mouse",
Description:"Lord Ganesha, the dear elephant-headed deity, is revered as the remover of obstacles and the god of new beginnings in Hinduism. Known as the son of Lord Shiva and Goddess Parvati, Ganesha is worshipped at the start of new ventures, ceremonies, and journeys to ensure success and remove any hindrances. Lord Ganesha serves as a spirit guide for those seeking to overcome challenges and embark on new paths. He embodies wisdom, prosperity, and good fortune, and his blessings are sought for intellectual pursuits and overcoming challenges. Ganesha’s iconic image, with his large head symbolizing wisdom and his small eyes representing focus, inspires devotees to seek his guidance for spiritual growth, knowledge, and the successful completion of endeavors.",
Guidance:"Drawing the card of Lord Ganesha as your spirit guide signifies a time to embrace new beginnings and remove obstacles from your life. His message encourages you to approach challenges with confidence and seek new opportunities with an open heart. Engage in practices that enhance your ability to overcome obstacles and invite prosperity, such as setting clear intentions, visualizing success, and invoking Ganesha's blessings. Lord Ganesha reminds you that through determination and positive action, you can navigate any difficulties and create a successful path forward.",
Affirmation:
"I embrace new beginnings and surrender all obstacles. With Lord Ganesha's guidance, I clear my path and invite success and prosperity.",
 Invocation: "Divine Lord Ganesha, revered Remover of Obstacles, I seek your grace and guidance. Illuminate my path and reveal the true possibilities hidden in my challenges. Help me to overcome the hurdles in my life with wisdom and ease. Grant me clarity, strength, and the courage to navigate these trials. May your divine presence lead me to success and harmony, aligning my journey with purpose and peace.",

      },
      { id:41,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625344/40_ganesha_ftuxul.jpg',
      },
      { id:42,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625341/42_sita_ram_cg8bzi.jpg',
        Message: "Embody Love, Devotion, and Consciousness.",
Colour: "Royal Blue and Soft Gold",
CrystalorDivinationTool: "Blue Sapphire and Peridot",
Description:"Sita Ram, the sacred union of Lord Ram and Goddess Sita, represents the perfect balance of divine masculine and feminine energies. Together, they symbolize love, devotion, and the unwavering strength of dharma (righteousness). Lord Ram tands as the protector and embodiment of truth and virtue, while Goddess Sita radiates grace, resilience, and devotion. Their story from the Ramayana serves as a guide for leading a life of purpose, integrity, and selfless love. Sita Ram inspires seekers to navigate life’s trials with courage, trust, and mutual respect, reminding us that strength and compassion together lead to divine harmony.",
Guidance:"Drawing the card of Sita Ram as your spirit guide signifies a time to align your actions with dharma and nurture your relationships with love and devotion. Their message encourages you to seek balance and purpose in your life. Embrace the qualities of compassion, courage, and grace, and allow their divine energy to guide you through challenges, helping you stay true to your values. Sita Ram reminds you that in union and mutual respect lies the strength to overcome adversity and achieve spiritual growth.",
Affirmation:"I embody love, devotion, and righteousness. With Sita Ram’s guidance, I walk the path of dharma with courage and grace.",
Invocation: "Dear Sita Ram, divine embodiment of love and dharma, guide me with courage, grace,and resilience. Guide me to walk the path of dharma with courage and grace. Fill my heart with compassion and help me honour strength and devotion. Bless me with harmony, wisdom, and purpose on my spiritual journey."

      },
      { id:43,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625331/43_Hanuman_fmxjjt.jpg',
        Message: "Adopt Strength, Devotion, and Faith.",
Colour: "Orange and Red",
CrystalorDivinationTool: "Red Jasper",
Description:"Lord Hanuman, the revered monkey deity in Hinduism, is celebrated as the embodiment of strength, devotion, and unwavering loyalty. Known for his immense physical prowess and his devotion to Lord Rama, Hanuman is a symbol of selfless service, courage, and the power of faith. His role in the epic Ramayana, where he plays a crucial part in the rescue of Sita and the defeat of the demon king Ravana, highlights his dedication and bravery. Hanuman is worshipped as a protector, and his blessings are sought to overcome obstacles, gain strength, and stay committed to one’s duties. His devotees find inspiration in his qualities of humility, wisdom, and boundless energy.",
Guidance:"Drawing the card of Lord Hanuman as your spirit guide signifies a time to embrace strength, devotion, and unwavering faith. His message encourages you to face challenges with courage and maintain steadfast devotion in your endeavors. Engage in practices that enhance your spiritual and physical strength, such as prayer, chanting, physical exercise, and acts of service. Lord Hanuman reminds you that through unwavering faith and dedication, you can overcome any obstacle and achieve greatness.",
Affirmation:"I embrace strength, devotion, and unwavering faith. With Lord Hanuman's guidance, I face challenges with courage and dedication.",
Invocation: "Dear Lord Hanuman, Divine Protector, hear my humble plea. Illuminate my path and grant me strength in my times of need. Help me overcome challenges with courage and wisdom.Shield me from harm and guide me with your unwavering support. Empower me to act with compassion and resolve, reflecting your divine qualities. May your blessings lead me to a life of peace and purpose."

      },
      { id:44,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625346/44_Dhanvantri_jwtfej.jpg',
        Message: "Embrace the Healing Power Within.",
Colour: "Emerald Green",
CrystalorDivinationTool: "Green Aventurine",
Description:"Dhanvantri, the divine physician and god of Ayurveda in Hindu mythology, is revered as the source of all healing and medicine. Emerging during the churning of the ocean (Samudra Manthan) with the pot of Amrita, the nectar of immortality, Dhanvantri is honored as the patron of health, wellness, and longevity. His teachings form the foundation of Ayurveda, the ancient Indian system of natural healing. Worshipped for his ability to cure diseases and promote vitality, Dhanvantari is a symbol of life, health, and the eternal pursuit of balance between mind, body, and spirit.",
Guidance:"Drawing the card of Dhanvantri as your spirit guide signifies a time to embrace your healing abilities and focus on wellness. His message encourages you to trust in your innate power to heal and rejuvenate. Engage in practices that enhance your health and spiritual growth, such as meditation, studying Ayurveda, and exploring natural healing methods. Dhanvantri reminds you that you have the power to heal yourself and others through focused intention and holistic practices.",
Affirmation:
"I embrace my healing abilities and vibrant health. With Dhanvantri's guidance, I unlock the power of wellness and rejuvenation within me.",
Invocation: "Dear Lord Dhanvantri, reveal the path to healing and well-being within my soul. Illuminate the areas of my life that require restoration and balance. Guide me towards physical and spiritual vitality, offering your divine assistance. Help me embrace health and wholeness, living with purpose and grace. May your wisdom inspire me to nurture my body and spirit in harmony."

      },
      { id:45,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625344/45_spirit_a_tnohep.jpg',
        Message: "Open to the Wisdom and Power of Your Animal Guide.",
Colour: "Varies by Animal",
CrystalorDivinationTool : "Animals are themselves",
Description:"Your spirit animal serves as a guide, offering wisdom, protection, and insights into your natural instincts and personal strengths. Each spirit animal embodies unique qualities and lessons that can help you navigate life's challenges and embrace your true nature. Each spirit animal is believed to offer unique lessons, reflecting aspects of one's personality or circumstances. For example, the wolf symbolizes leadership and intuition, while the owl represents wisdom and insight. People often feel drawn to specific animals that resonate with their life experiences or spiritual journey. Spirit animals serve as reminders of the natural world's connection to our inner selves, guiding us to embrace the quantities they represent, such as courage, adaptability, or inner peace.",
Guidance:"Drawing the card of your spirit animal signifies a time to embrace the wisdom and power of your natural guide. The message encourages you to connect with the qualities of your spirit animal and apply its lessons to your life. Engage in practices that enhance your connection to your spirit animal, such as meditation, visualization, and studying the animal's characteristics and behaviours. Your spirit animal reminds you that through understanding and embodying its traits, you can navigate life with greater confidence and insight.",
Affirmation:
"I embrace the wisdom and power of my spirit animal. With its guidance, I connect with my natural instincts and strengths.",
 
Invocation: "Great Spirit Animal, guide of ancient wisdom, I call upon you to reveal the truths hidden within the natural world. Illuminate my path with your timeless knowledge and insight, showing me how to align with the flow of nature’s wisdom. May your presence bring clarity, healing, and harmony to my journey, guiding me towards greater understanding and purpose.",

      },
      { id:46,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625334/46_guardian_a_yqszlq.jpg',
        Message: "Unite with the Protection and Guidance of your Guardian Angel.",
Colour: "Specific to your Guardian Angel",
CrystalorDivinationTool: "Celestite and Angelite",
Description:"Your guardian angels are divine protector and guides, offering you constant support, love, and guidance. Their presence is symbolised by the serene white colours or their respective colour, representing purity, divine light, and heavenly protection. Your guardian angel watches over you,helping you navigate life's challenges and offering wisdom and comfort in times of need. They encourage you to connect with their loving energy, helping you to feel safe and guided.",
Guidance:"Drawing the card of your guardian angel signifies a time to embrace the protection and guidance that is always available to you. Their message encourages you to trust in their presence and seek their support whenever you need it. Engage in practices that enhance your connection to your guardian angel, such as prayer, meditation, and expressing gratitude. Your guardian angel reminds you that through trust and openness, you can receive their loving guidance and protection in all aspects of your life.",
Affirmation:"I embrace the protection and guidance of my guardian angels. With their loving support, I feel safe, guided, and deeply loved.",
Invocation: "Dear Guardian Angel, divine protector, I call upon your sacred presence. Illuminate the path ahead and shield me from any harm. Guide me through challenges with your gentle strength and wisdom. Help me find solace and clarity in moments of uncertainty. May your protective grace surround me, fostering peace and courage within.",

      },
      { id:47,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625347/47_shaman_jycqne.jpg',
        Message: "Explore the Ancient Wisdom and Healing Power.",
Colour: "Earthy Browns and Greens",
CrystalorDivinationTool: "Smoky Quartz, Drum, Feathers",
Description:"Shamans, the wise healers and spiritual leaders of indigenous traditions, embody the essence of ancient wisdom, healing, and deep connection to the natural world. Their presence is symbolized by earthy browns and greens, representing grounding,growth, and the harmony of the earth. Shamans serve as spirit guides for those seeking to heal, transform, and connect with the spiritual realms. They encourage you to embrace their teachings, helping you to unlock the healing power within and connect with the spirit of nature. The energy of shamans is one of profound healing and spiritual guidance, making them powerful allies for those on a journey of holistic wellness and spiritual awakening.",
Guidance:"Drawing the card of shamans as your spirit guides signifies a time to embrace ancient wisdom and healing practices. Their message encourages you to connect with the natural world and seek holistic healing. Engage in practices that enhance your spiritual and physical well-being, such as meditation, herbal medicine, drumming, and connecting with nature spirits. Shamans remind you that through harmony with nature and spiritual practice, you can achieve deep healing and transformation.",
Affirmation:
"I embrace the ancient wisdom and healing power of the shamans. With their guidance, I connect with nature and unlock my inner healing abilities and innate potencies.",
 
Invocation: "Wise Shamans, I call upon you. Guide me through the depths of my heart, illuminating my path with your ancient wisdom. Help me recognise and embrace the healing I need. May your sacred knowledge awaken new insights and transform my pain into growth. Lead me toward a life of harmony, clarity, and purpose, embodying your spirit of compassion and timeless guidance."

      },
      { id:48,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625344/48_Ancestors_ciutum.jpg',
        Message: "Your Roots hold the Keys to your Growth.",
Colour: "Deep Earth Tones",
CrystalorDivinationTool: "Ancestralite or family totem",
Description:"Your ancestors, the lineage of your family and spiritual heritage, embody the essence of ancient wisdom, strength, and continuity. Often regarded as wise and protective figures who continue to influence the lives of their descendants. In many cultures, ancestors are honoured and revered through rituals, offerings, and prayers, as they are believed to provide guidance, protection, and blessings. By honouring and remembering them, individuals can draw strength from their ancestors' experiences and wisdom, fostering a deep sense of belonging, continuity, and support on their life journey. Your ancestors serve as spirit guides, offering you guidance, protection, and insights drawn from their experiences and wisdom.",
Guidance:"Drawing the card of your ancestors signifies a time to embrace the wisdom and guidance that flows from your lineage. Their message encourages you to connect with your heritage and seek insights from the experiences of those who came before you. Engage in practices that honour your ancestors and deepen your connection to your roots, such as ancestral rituals, storytelling, and genealogical research. Your ancestors remind you that through honouring your heritage and seeking their guidance, you can find strength, wisdom, and a sense of belonging.",
Affirmation:"I embrace the guidance and wisdom of my ancestors. With their support, I honour my heritage and draw strength from my roots.",
 
Invocation: "Great Ancestors, hear my call and bring forth the wisdom of your ages. Illuminate my path with your deep knowledge and guide me through the shadows of my journey. Help me embrace the lessons of the past, to heal and grow with clarity and grace. Empower me to honor your legacy, living with intention, love, and a renewed sense of purpose.",

      },
      { id:49,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625344/49_Parents_veclmd.jpg',
        Message: "Implement Forgiveness and Gratitude with your Origin in this Life.",
Colour: "Soft Pink",
CrystalorDivinationTool: "Rose Quartz",
Description:"Your parents, the immediate caregivers and guides of your life, embody the essence of unconditional love, nurturing, and wisdom. Your parents serve as spirit guides, offering you love, support, and valuable life lessons drawn from their experiences. They encourage you to honour their teachings and embrace their guidance, helping you navigate your life's journey with love and wisdom. The energy of your parents is one of profound care and nurturing, making them powerful allies for those seeking to strengthen their familial bonds and draw upon parental wisdom.",
Guidance:"Drawing the card of your ancestors signifies a time to embrace the wisdom and guidance that flows from your lineage. Their message encourages you to connect with your heritage and seek insights from the experiences of those who came before you. Engage in practices that honour your ancestors and deepen your connection to your roots, such as ancestral rituals, storytelling, and genealogical research. Your ancestors remind you that through honouring your heritage and seeking their guidance, you can find strength, wisdom, and a sense of belonging.",
Affirmation:
"I embrace the love, wisdom, and guidance of my parents. I honour our bond and draw strength from their teachings.",
Invocation: "Invocation of Parents' Energy `Dear Parents, `I call upon your loving presence. Surround me with your unconditional love and nurturing strength. Guide me with the wisdom of your life’s experiences and the values you have instilled in me. Help me to honor our shared lineage, heal past wounds, and embrace the power of forgiveness. Your energy lives with me, and I trust in its power to lead me toward growth, harmony, and peace.",

      },
      { id:50,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625345/50_fairies_mroqqy.jpg',
        Message: "Immerse in the Magic and Joy of the Natural World.",
Colour: "Many Colours",
CrystalorDivinationTool: "Green Aventurine and Fairy Stone",
Description:"Fairies, the enchanting guardians of nature, embody the essence of magic, joy, and the playful spirit of the natural world. Their presence is symbolized by light green colour, representing growth, enchantment, and the vibrant energy of nature. Fairies serve as spirit guides for those seeking to connect with the magic of the earth, enhance their creativity, and find joy in the little things. They encourage you to embrace their playful energy, helping you to see the world through a lens of wonder and enchantment. The energy of fairies is one of joyful guidance and natural harmony, making them powerful allies for those on a journey of creative expression and connection with nature.",
Guidance:"Drawing the card of fairies signifies a time to embrace the magic and joy of the natural world. Their message encourages you to connect with nature and find delight in its beauty. Engage in practices that enhance your creativity and connection to the earth, such as spending time outdoors, gardening, and creating art inspired by nature. Fairies remind you that through playfulness and enchantment, you can bring more joy and magic into your life.",
Affirmation:
"I embrace the magic and joy of the natural world. With the guidance of the fairies, I connect with nature and enhance my creativity.",
Invocation: "Dear Fairies, gentle and wise guardians of the magical realms, I invite your enchanting presence into my life. Please reveal the hidden blessings and guide me with your light. Assist me in transforming challenges into opportunities for growth and joy. May your grace help me see beauty in every moment and inspire me to live harmoniously with the wonders around me. Thank you for your guidance and wisdom.",

      },
      { id:51,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625345/51_Phoenix_qmsbq1.jpg',
        Message: "Rise from the Ashes and Emerge as New You.",
Colour: "Fiery Red and Gold",
CrystalorDivinationTool: "Fire Agate",
Description:"Phoenix, the legendary bird of fire, is a powerful symbol of rebirth, transformation, and eternal life. In mythology, the Phoenix is known for its ability to rise from its own ashes, reborn anew in a cycle of death and resurrection. This divine creature embodies the energy of renewal, reminding us that from the ashes of our challenges and struggles, we have the power to emerge stronger, wiser, and more vibrant. The fiery red and gold colors of the Phoenix represent its dynamic energy and the warmth of its transformative fire. As a spiritual guide, the Phoenix encourages you to embrace change, let go of the past, and trust in the process of renewal.",
Guidance:"Drawing the card of the Phoenix signifies a time of profound transformation and rebirth. The Phoenix’s message is one of courage and resilience, urging you to embrace the changes in your life and trust that they are leading you to a new beginning. Engage in practices that help you release what no longer serves you, such as journaling, meditation, or rituals of letting go. The Phoenix reminds you that every ending is a new beginning and that through the fires of transformation, you can rise anew with greater strength and clarity.",
Affirmation:
"I embrace the power of transformation. Like the Phoenix, I rise from the ashes with renewed strength and wisdom.",
Invocation: "Phoenix, magnificent bird of fire, I call upon your power of transformation. Help me to rise from the ashes of my past with renewed strength and clarity. Guide me through the fires of change,and lead me to a life of rebirth and renewal. May your eternal flame burn brightly within me, inspiring me to embrace each new beginning with courage and grace. Thank you for your wisdom and guidance.",

      },
      { id:52,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625347/52_Mermaid_owk5b5.jpg',
        Message: "Align with Emotional Flow and Intuitive Wisdom.",
Colour: "Aquatic Blue and Silver",
CrystalorDivinationTool: "Aquatic Blue and Silver",
Description:"Mermaids are enchanting water spirits known for their beauty, grace, and deep connection to the oceans. Often depicted with the upper body of a human and the tail of a fish, mermaids embody the mystery and allure of the sea. They are associated with emotions, intuition, and the subconscious,guiding those who seek to explore their inner depths and embrace their true feelings. Mermaids are protectors of the oceans and all its creatures, symbolizing the balance between the human and natural worlds. Their presence encourages emotional healing, self-discovery, and a harmonious relationship with nature, making them powerful guides for those on a journey of emotional and spiritual growth.",
Guidance:"Drawing the card of mermaids signifies a time to embrace emotional flow and intuitive wisdom. Their message encourages you to trust in your emotions and listen to your inner voice. Engage in practices that enhance your emotional and intuitive connection, such as spending time near water, practicing meditation, and working with crystals. Mermaids remind you that through emotional flow and intuitive insight, you can achieve healing and transformation.",
Affirmation:
"I embrace emotional flow and intuitive wisdom. With the guidance of the mermaids, I connect deeply with my emotions and trust my inner guidance.",
Invocation: "Graceful Mermaid, guardian of the water’s wisdom, I call upon your serene energy.Reveal the truths hidden beneath the surface of my emotions and desires. Help me to navigate the depths of my inner world with clarity and ease. Guide me in transforming challenges into flow and harmony. Assist me in embracing the wisdom of the water, living with fluidity and grace in all aspects of my life.",

      },
      { id:53,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625347/53_Tree_Spirit_yqom0y.jpg',
        Message: "Cultivate Stability, Growth and Deep- Rooted Wisdom.",
Colour: "Forest Green and Brown",
CrystalorDivinationTool: "Tree Agate, Leaf or Twig",
Description:"Tree spirits, also known as dryads or tree guardians, are ethereal beings that embody the life force of trees and forests. Deeply connected to nature, these spirits are protectors of the woodlands, nurturing growth and maintaining balance within their ecosystems. Tree spirits are ancient and wise,holding the knowledge of the earth's history and the secrets of life. They symbolize stability, strength, and endurance, offering guidance to those who seek a deeper connection with nature. By communicating with tree spirits, individuals can gain insight into natural cycles, healing, and grounding energies. These spirits encourage respect for the environment and a harmonious relationship with the natural world.",
Guidance:"Drawing the card of tree spirits signifies a time to embrace stability, growth, and deep-rooted wisdom. Their message encourages you to connect with the grounding energy of the earth and seek inner strength. Engage in practices that enhance your connection to nature, such as spending time in forests, practicing grounding exercises, and working with crystals. Tree spirits remind you that through stability and steady growth, you can achieve profound personal development and spiritual insight.",
Affirmation:
"I embrace stability, growth, and deep-rooted wisdom. With the guidance of the tree spirits, I connect deeply with nature and cultivate inner strength.",
Invocation: "Wise Tree Spirits, guardians of growth and wisdom, I call upon you to hear the whispers of my heart. Illuminate the path to my deepest needs and desires. As you nurture the earth, guide me through life's transitions with clarity and strength. Help me grow with grace, embracing change and renewal. Bless me with your wisdom, so I may flourish in harmony and purpose.",

      },
      { id:54,
        frontImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625336/00_Back_card_upxqkz.jpg',
        backImage: 'https://res.cloudinary.com/dwiil16oj/image/upload/v1737625347/53_Tree_Spirit_yqom0y.jpg',
        Message: "The Power You Seek is within YOU.",
Colour: "Golden White",
CrystalorDivinationTool: "Journal and Mirror",
Description:"You, as a divine reflection, embodies the essence of inner wisdom, spiritual clarity, and the boundless light that resides within each individual. This divinity is symbolised by a golden white light, representing purity, enlightenment, and the infinite potential of the soul. You serves as a powerful reminder that divinity is not something external, but a profound presence within, waiting to be acknowledged and embraced. This divine essence guides you towards self-realization, helping you unlock the wisdom and spiritual strength that are inherent to your being. The energy of You is one of empowerment and inner peace, making it a guiding force for those on a path of spiritual awakening and personal transformation.",
Guidance:"Drawing the card of You signifies a time to turn inward and embrace the divine light that resides within. This message encourages you to trust in your inner wisdom and recognize the spiritual power that flows through you. Engage in practices that nurture your connection with your inner self, such as meditation, self-reflection, and spiritual study. You reminds you that by embracing your inner divinity, you can bring clarity, purpose, and peace into your life.",
Affirmation:
"I embrace the divine light within me. With my inner guidance, I unlock the wisdom and spiritual clarity that illuminate my path.",
Invocation: "Divine essence within me, I call upon your infinite wisdom and light. Guide me on my journey of self-discovery and spiritual growth. Help me to embrace the divine reflection within myheart. Illuminate my path with your radiant light, and lead me to live a life of grace, purpose, and clarity. May I always remember that the divine flows through me, connecting me to the universe and all its wonders."

      },
     
   
  ];
  